# Generated by Django 5.0.6 on 2024-06-07 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GolfClub",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("club_id", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="GolfCourse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("course_id", models.CharField(max_length=100)),
                (
                    "golf_club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="golf.golfclub"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TeeTime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time", models.DateTimeField()),
                ("tee_time_id", models.CharField(max_length=100)),
                ("availability", models.CharField(max_length=100)),
                ("available_spots", models.IntegerField()),
                ("expired", models.BooleanField()),
                (
                    "golf_course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="golf.golfcourse",
                    ),
                ),
            ],
        ),
    ]
