# Generated by Django 5.0.6 on 2024-06-07 19:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("golf", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="golfclub",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="golfclub",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
