# Generated by Django 5.0.6 on 2024-06-07 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("golf", "0002_alter_golfclub_latitude_alter_golfclub_longitude"),
    ]

    operations = [
        migrations.AlterField(
            model_name="golfcourse",
            name="golf_club",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="golf_courses",
                to="golf.golfclub",
            ),
        ),
    ]
