# Generated by Django 5.0.6 on 2024-06-08 15:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("golf", "0004_remove_teetime_tee_time_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="golfclub",
            name="created",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="golfcourse",
            name="created",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="teetime",
            name="last_updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
