# Generated by Django 5.0.6 on 2024-07-06 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("golf", "0005_golfclub_created_golfcourse_created_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GolfBoxCookie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("value", models.TextField()),
                ("expires", models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
