# Generated by Django 5.0.6 on 2024-07-06 20:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("golf", "0006_golfboxcookie"),
    ]

    operations = [
        migrations.AlterField(
            model_name="golfclub",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
