# Generated by Django 5.0.6 on 2024-07-06 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("golf", "0007_alter_golfclub_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="golfcourse",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
