# Generated by Django 5.0.6 on 2024-07-06 20:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("golf", "0010_golfcourse_price_in_ore"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="golfcourse",
            name="price_in_ore",
        ),
        migrations.AddField(
            model_name="teetime",
            name="price_in_ore",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(10000),
                ],
            ),
        ),
    ]
