# Generated by Django 5.1.5 on 2025-03-08 23:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("golf", "0011_remove_golfcourse_price_in_ore_teetime_price_in_ore"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teetime",
            name="price_in_ore",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(1000000),
                ],
            ),
        ),
    ]
