# Generated by Django 5.0.6 on 2025-04-22 20:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("golf", "0012_alter_teetime_price_in_ore"),
    ]

    operations = [
        migrations.CreateModel(
            name="SearchQuery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("query", models.TextField()),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
