# Generated by Django 5.0.6 on 2025-04-22 20:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("golf", "0013_searchquery"),
    ]

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
            ],
        ),
    ]
