# Generated by Django 5.1.5 on 2025-05-06 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("golf", "0014_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teetime",
            name="golf_course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tee_times",
                to="golf.golfcourse",
            ),
        ),
    ]
